# Generated by Django 5.0.6 on 2025-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('system_admin', 'Owner'), ('manager', 'Admin'), ('user', 'Member'), ('developer', 'Developer'), ('invited', 'Invited')], default='user', max_length=20),
        ),
    ]
