# Generated by Django 5.0.6 on 2025-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('developer', 'Developer'), ('system_admin', 'System Admin')], default='user', max_length=20),
        ),
    ]
